// generated by stringer -type=event; DO NOT EDIT

package main

import "fmt"

const _event_name = "EV_TICK"

var _event_index = [...]uint8{0, 7}

func (i event) String() string {
	if i < 0 || i+1 >= event(len(_event_index)) {
		return fmt.Sprintf("event(%d)", i)
	}
	return _event_name[_event_index[i]:_event_index[i+1]]
}
