// Code generated by "stringer -type=event"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EV_ERROR-0]
	_ = x[EV_CONNECTED-1]
	_ = x[EV_ACTOR_ALREADY_CONNECTED-2]
	_ = x[EV_ACTOR_DOESNT_EXIST-3]
	_ = x[EV_ACTOR_EXISTS-4]
	_ = x[EV_AUTH_FAILED-5]
	_ = x[EV_LOGIN_SUCCESS-6]
	_ = x[EV_CREATE_SUCCESS-7]
	_ = x[EV_RECV_INPUT_CONN-8]
	_ = x[EV_RECV_INITIAL_STATE-9]
	_ = x[EV_RECV_UPDATE-10]
	_ = x[EV_RECV_CHAT_SAY-11]
	_ = x[EV_SENT_CHAT_SAY-12]
	_ = x[EV_TERRAIN_RESET-13]
	_ = x[EV_TERRAIN_CANVAS_SHIFT-14]
	_ = x[EV_TERRAIN_DRAW_TILE-15]
	_ = x[EV_SIZE-16]
}

const _event_name = "EV_ERROREV_CONNECTEDEV_ACTOR_ALREADY_CONNECTEDEV_ACTOR_DOESNT_EXISTEV_ACTOR_EXISTSEV_AUTH_FAILEDEV_LOGIN_SUCCESSEV_CREATE_SUCCESSEV_RECV_INPUT_CONNEV_RECV_INITIAL_STATEEV_RECV_UPDATEEV_RECV_CHAT_SAYEV_SENT_CHAT_SAYEV_TERRAIN_RESETEV_TERRAIN_CANVAS_SHIFTEV_TERRAIN_DRAW_TILEEV_SIZE"

var _event_index = [...]uint16{0, 8, 20, 46, 67, 82, 96, 112, 129, 147, 168, 182, 198, 214, 230, 253, 273, 280}

func (i event) String() string {
	if i < 0 || i >= event(len(_event_index)-1) {
		return "event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _event_name[_event_index[i]:_event_index[i+1]]
}
