// generated by stringer -type=ChatRequestType; DO NOT EDIT

package game

import "fmt"

const _ChatRequestType_name = "CR_ERRORCR_SAYCR_SIZE"

var _ChatRequestType_index = [...]uint8{0, 8, 14, 21}

func (i ChatRequestType) String() string {
	if i < 0 || i+1 >= ChatRequestType(len(_ChatRequestType_index)) {
		return fmt.Sprintf("ChatRequestType(%d)", i)
	}
	return _ChatRequestType_name[_ChatRequestType_index[i]:_ChatRequestType_index[i+1]]
}
