// Code generated by "stringer -type=ChatRequestType"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CR_ERROR-0]
	_ = x[CR_SAY-1]
	_ = x[CR_SIZE-2]
}

const _ChatRequestType_name = "CR_ERRORCR_SAYCR_SIZE"

var _ChatRequestType_index = [...]uint8{0, 8, 14, 21}

func (i ChatRequestType) String() string {
	if i < 0 || i >= ChatRequestType(len(_ChatRequestType_index)-1) {
		return "ChatRequestType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChatRequestType_name[_ChatRequestType_index[i]:_ChatRequestType_index[i+1]]
}
