// generated by stringer -type=EncodedType; DO NOT EDIT

package game

import "fmt"

const _EncodedType_name = "ET_ERRORET_DISCONNECTET_REQ_LOGINET_REQ_CREATEET_RESP_AUTH_FAILEDET_RESP_ACTOR_EXISTSET_RESP_ACTOR_DOESNT_EXISTET_RESP_LOGIN_SUCCESSET_RESP_CREATE_SUCCESSET_WORLD_STATEET_WORLD_STATE_DIFF"

var _EncodedType_index = [...]uint8{0, 8, 21, 33, 46, 65, 85, 111, 132, 154, 168, 187}

func (i EncodedType) String() string {
	if i < 0 || i+1 >= EncodedType(len(_EncodedType_index)) {
		return fmt.Sprintf("EncodedType(%d)", i)
	}
	return _EncodedType_name[_EncodedType_index[i]:_EncodedType_index[i+1]]
}
