// generated by stringer -type=EncodedType; DO NOT EDIT

package game

import "fmt"

const _EncodedType_name = "ET_ERRORET_DISCONNECTET_REQ_LOGINET_REQ_CREATEET_RESP_ACTOR_ALREADY_CONNECTEDET_RESP_AUTH_FAILEDET_RESP_ACTOR_EXISTSET_RESP_ACTOR_DOESNT_EXISTET_RESP_LOGIN_SUCCESSET_RESP_CREATE_SUCCESSET_REQ_CONNECTET_CONNECTEDET_WORLD_STATEET_WORLD_STATE_DIFFET_REQ_MOVEET_REQ_USEET_REQ_CHAT"

var _EncodedType_index = [...]uint16{0, 8, 21, 33, 46, 77, 96, 116, 142, 163, 185, 199, 211, 225, 244, 255, 265, 276}

func (i EncodedType) String() string {
	if i < 0 || i+1 >= EncodedType(len(_EncodedType_index)) {
		return fmt.Sprintf("EncodedType(%d)", i)
	}
	return _EncodedType_name[_EncodedType_index[i]:_EncodedType_index[i+1]]
}
