// generated by stringer -type=RequestMsg; DO NOT EDIT

package game

import "fmt"

const _RequestMsg_name = "REQ_LOGINREQ_CREATE"

var _RequestMsg_index = [...]uint8{0, 9, 19}

func (i RequestMsg) String() string {
	if i < 0 || i+1 >= RequestMsg(len(_RequestMsg_index)) {
		return fmt.Sprintf("RequestMsg(%d)", i)
	}
	return _RequestMsg_name[_RequestMsg_index[i]:_RequestMsg_index[i+1]]
}
