// generated by stringer -type=updateType; DO NOT EDIT

package game

import "fmt"

const _updateType_name = "UT_UPDATE_FULLUT_UPDATE_DIFF"

var _updateType_index = [...]uint8{0, 14, 28}

func (i updateType) String() string {
	if i < 0 || i+1 >= updateType(len(_updateType_index)) {
		return fmt.Sprintf("updateType(%d)", i)
	}
	return _updateType_name[_updateType_index[i]:_updateType_index[i+1]]
}
