// generated by stringer -type=UseRequestType; DO NOT EDIT

package game

import "fmt"

const _UseRequestType_name = "UR_ERRORUR_USEUR_USE_CANCELUR_SIZE"

var _UseRequestType_index = [...]uint8{0, 8, 14, 27, 34}

func (i UseRequestType) String() string {
	if i < 0 || i+1 >= UseRequestType(len(_UseRequestType_index)) {
		return fmt.Sprintf("UseRequestType(%d)", i)
	}
	return _UseRequestType_name[_UseRequestType_index[i]:_UseRequestType_index[i+1]]
}
