// Code generated by "stringer -type=TerrainShift"; DO NOT EDIT.

package canvas

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TS_NORTH-0]
	_ = x[TS_NORTHEAST-1]
	_ = x[TS_EAST-2]
	_ = x[TS_SOUTHEAST-3]
	_ = x[TS_SOUTH-4]
	_ = x[TS_SOUTHWEST-5]
	_ = x[TS_WEST-6]
	_ = x[TS_NORTHWEST-7]
}

const _TerrainShift_name = "TS_NORTHTS_NORTHEASTTS_EASTTS_SOUTHEASTTS_SOUTHTS_SOUTHWESTTS_WESTTS_NORTHWEST"

var _TerrainShift_index = [...]uint8{0, 8, 20, 27, 39, 47, 59, 66, 78}

func (i TerrainShift) String() string {
	if i < 0 || i >= TerrainShift(len(_TerrainShift_index)-1) {
		return "TerrainShift(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TerrainShift_name[_TerrainShift_index[i]:_TerrainShift_index[i+1]]
}
